# Generated by Django 3.0.2 on 2020-01-19 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('W', 'Female')], max_length=20)),
                ('height', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
